export const REDUCER_CONSTANTS = {
    CART_ADD_ITEM: 'CART_ADD_ITEM',
    CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
    GET_PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    LOGIN: 'AUTH_LOGIN',
    LOGOUT: 'AUTH_LOGOUT',
    CART_PLUS: 'CART_PLUS',
    CART_MINUS: 'CART_MINUS',
    GET_COUNTRYLIST_SUCCESS: 'GET_COUNTRYLIST_SUCCESS',
    GET_COUNTRYLIST_FAILURE: 'GET_COUNTRYLIST_FAILURE',

}